walking_tour/config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :tours do
    resources :locations
    resources :users
    resources :categories
  end

  resources :users
  resources :categories

end

walking_tour/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tours
  validates :category, presence: true

end

walking_tour/app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :tour

  validates :location_title, presence: true
  validates :location_address, presence: true
  validates :location_description, presence: true
  validates :location_image, presence: true
  validates :tour_id, presence: true
end

walking_tour/app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :user
  has_many :locations
  belongs_to :category

  validates :city, presence: true
  validates :subject, presence: true
  validates :tour_title, presence: true
  validates :tour_title_description, presence: true
  validates :tour_title_image, presence: true

end

walking_tour/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tours

  validates :name, presence: true
  validates :url, presence: true
  validates :picture, presence: true
  validates :bio, presence: true
end

walking_tour/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

walking_tour/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

   def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

end

walking_tour/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

walking_tour/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  
def new
    @location = Location.new
    @tour = Tour.find(params[:tour_id])
end

def create
    tour = Tour.find(params[:tour_id])
    tour.locations << Location.create(params[:location].permit(:location_title, :location_address, :location_description, :location_image))

    redirect_to tour
  end
end

walking_tour/app/controllers/tours_controller.rb
class ToursController < ApplicationController

  def index
    @tours = Tour.all
  end
 
  def new
    @tour = Tour.new
  end 

  def create
    tour = Tour.new params[:tour].permit(:city, :subject, :tour_title, :tour_title_description, :tour_title_image)  
    if tour.save
      flash[:notice] = "Post successfully created"
      redirect_to tour_path(tour)
      # tours_path 
    else
      render 'new'
    end
  end

  def show
    @tour = Tour.find(params[:id])
  end

  def edit
    @tour = Tour.find(params[:id])
  end

  def destroy
    tour = Tour.find(params[:id])
    tour.destroy
    redirect_to(tours_path)
  end

  def update
    @tour = Tour.find(params[:id])
    @tour.update(tours_params)
    redirect_to(tours_path)
  end

  private
  def tours_params
    params.require(:tour).permit(:city, :subject, :tour_title, :tour_title_description, :tour_title_image)
  end

end

walking_tour/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user].permit(:name, :url, :picture, :bio)

  if @user.save
    flash[:notice] = "User successfully created"
    redirect_to users_path
    else
    render 'new' 
  end
end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to(users_path)
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
    redirect_to(users_path)
  end

  private
  def users_params
    params.require(:user).permit(:name, :url, :picture, :bio)
  end

end

walking_tour/app/helpers/application_helper.rb
module ApplicationHelper
end

walking_tour/app/helpers/categories_helper.rb
module CategoriesHelper
end

walking_tour/app/helpers/locations_helper.rb
module LocationsHelper
end

walking_tour/app/helpers/tours_helper.rb
module ToursHelper
end

walking_tour/app/helpers/users_helper.rb
module UsersHelper
end

walking_tour/app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>

  <% @categories.each do |category| %>
      <%= category.category %>
      <% category.tours.each do |tour| %>
          <%= tour.tour_title %>
       <% end %>
  <% end %>
</div>

walking_tour/app/views/home/index.html.erb
  <div class="jumbotron">
    <div class="container">
      <h1>Self-guided city walks.</h1> 
        <p class="lead">Self-guided tours for curious people. Explore cool, tasty, smart and strange parts of a city.</p> 
          <p class="btn-group">
            <%= link_to 'View Tours', tours_path, :class => "btn btn-success btn-lg" %>
            <%= link_to 'Create Tour', new_tour_path, :class => "btn btn-default btn-lg" %>
          </p> 
    </div>
  </div>

  <div class="container">

    <div class="col-md-4">
      <div class="thumbnail">
      <img src="http://www.chilterntravel.com/wp-content/uploads/2013/04/Natural-History-Museum.jpg" alt="science">
        <h3>Science and the City</h3>
          <p>A science tour of London for all ages.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>
      <!-- THUMBNAIL NEW -->
      <div class="thumbnail">
      <img src="http://cdn.pursuitist.com/wp-content/uploads/2014/09/Jimmy-Choo-To-Go-Public.jpg" alt="science">
        <h3>Shoes in Siam</h3>
          <p>A shoes shopping tour in Bangkok that takes you to six great stores.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>
      <!-- THUMBNAIL NEW -->
      <div class="thumbnail">
      <img src="http://mysticpolitics.com/wp-content/uploads/2012/07/what-the-french-revolution-tells-us-about-todays-activist-movements-e1342168521376-638x360.jpg" alt="science">
        <h3>French Revolution Walk in Paris</h3>
          <p>Have a dozen significant sites can be found within these four blocks of central Paris.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>

    </div>
    <div class="col-md-4">
      <div class="thumbnail">
      <img src="http://www.b-sidebywale.com/blogwp/wp-content/uploads/2011/08/IMG_0551.jpg" alt="science">
        <h3>Shoreditch Street Art</h3>
          <p>Every day new art pops up in Shoreditch.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>
      <!-- THUMBNAIL NEW -->
      <div class="thumbnail">
      <img src="http://www.gtpass.com/Content/Images/uploaded/chicago-architecture-cr-river-_10933060.jpg" alt="science">
        <h3>Architecture Tour of Chicago Skyscrapers</h3>
          <p>See the best big buildings in one of America's biggest cities in this self-guided adventure.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>


    </div>
    <div class="col-md-4">
      <div class="thumbnail">
      <img src="https://c1.staticflickr.com/9/8099/8656991764_e3301d546d_b.jpg" alt="science">
        <h3>Tokyo Noodles, Meat & Beer</h3>
          <p>Ebisu is a great neighbourhood in Tokyo to eat like a local.</p>
          <p><a href="#" class="btn btn-default" role="button">View</a></p>
      </div>
    </div>


  </div>

walking_tour/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalkingTour</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <link rel="stylesheet" type="text/css" href="stylesheets/custom.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js' %>
  <%= csrf_meta_tags %>
  
</head>
  <body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to('City Walks', root_path, class: 'navbar-brand text-muted') %>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to('Tours', tours_path) %></li>
          <li><%= link_to('Users', users_path) %></li>
          <li><%= link_to('Categories', categories_path) %></li>
        </ul>
      </div>
    </div>
  </div>

  <% flash.each do |name, msg| %>
    <div class="flash-message flash-message-<%= name %>">
      <%= msg %>
    </div>
  <% end %>
 
  <%= yield %>
  
  <div class="container">
      <div>
        <p>&copy; 2015 City Walks - By WDI Productions Inc.</p>
      </div>
    </div>
  </body>
</html>

walking_tour/app/views/locations/new.html.erb
<div class="container">
  <%= form_for [@tour, @location] do |form| %>
    
    <%= form.label :location_title %>
    <%= form.text_field :location_title %>

    <%= form.label :location_address %>
    <%= form.text_field :location_address %>

    <%= form.label :location_description %>
    <%= form.text_field :location_description %>

    <%= form.label :location_image %>
    <%= form.text_field :location_image %>

    <%= form.submit 'Add Location' %>
  <% end %>
</div>

walking_tour/app/views/tours/edit.html.erb
<div class="container">
   <%= form_for @tour do |form| %>
      <% form.label :city %>
      <%= form.text_field :city %>
      
      <% form.label :subject %>
      <%= form.text_field :subject %>
      
      <% form.label :tour_title %>
      <%= form.text_field :tour_title %>
      
      <% form.label :tour_title_description %>
      <%= form.text_field :tour_title_description %>
      
      <% form.label :tour_title_image %>
      <%= form.text_field :tour_title_image %>
    
    <%= form.submit 'Save' %>
   <% end %>
</div>

walking_tour/app/views/tours/index.html.erb
<div class="container">

  <% @tours.each do |tour| %>
      <%= image_tag(tour.tour_title_image, width: 200) %>
      <h3><%= link_to tour.tour_title, tour_path(tour) %></h3>
      <p><%= link_to('EDIT', edit_tour_path(tour.id)) %></p>
      <p><%= link_to('DELETE', tour_path(tour.id), method: :delete) %></p>
  <% end %>
</div>

walking_tour/app/views/tours/new.html.erb
<div class="container">
   <%= bootstrap_form_for @tour do |form| %>
      <div class="panel-body">
      <% form.label :city %>
      <%= form.text_field :city %>
      
      <% form.label :subject %>
      <%= form.text_field :subject %>
      
      <% form.label :tour_title %>
      <%= form.text_field :tour_title %>
      
      <% form.label :tour_title_description %>
      <%= form.text_field :tour_title_description %>
      
      <% form.label :tour_title_image %>
      <%= form.text_field :tour_title_image %>



      <%= collection_select(:tour, :category_id, Category.all, :id, :category, prompt: true) %>

      <%= form.submit 'Save', class: 'btn btn-default' %>
      </div>

   <% end %>
</div>

walking_tour/app/views/tours/show.html.erb
<div class="container">
  <div class="col-md-8">
    <h1><%= @tour.tour_title %></h1>
    <h3><%= @tour.city %> | <%= @tour.subject %></h3>
    <h4><%= @tour.tour_title_description %></h4>
    <hr>
  </div>
  <!-- Column for the User who created the tour -->
  <div class="col-md-4">
    <%= image_tag(@tour.tour_title_image, width: 200) %>
  </div>
</div>



<div class="container">
  <div class="col-md-8">  
    <% @tour.locations.each do |location| %>
      <!-- <p>location was added <%= time_ago_in_words(location.created_at) %> ago</p> -->
      <h2><%= location.location_title %></h2>
      <h4><%= location.location_address %></h4>
      <p><%= location.location_description %></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <% @tour.locations.each do |location| %>  
    <%= image_tag(location.location_image, width: 250) %>
    <% end %>
  </div>
</div>

<div class="container">
  <%= link_to 'Add Location', new_tour_location_path(@tour) %>
</div>

walking_tour/app/views/users/edit.html.erb
<div class="container">
  <%= form_for @user do |form| %>

     <%= form.label :name %>
     <%= form.text_field :name %>
     
     <%= form.label :url %>
     <%= form.text_field :url %>
     
     <%= form.label :picture %>
     <%= form.text_field :picture %>
     
     <%= form.label :bio %>
     <%= form.text_field :bio %>
   
   <%= form.submit 'Save' %>

  <% end %>
</div>

walking_tour/app/views/users/index.html.erb
<div class="container">

   <% @users.each do |user| %>
     <div class="user-edit-delete">
      <p><%= link_to user.name, user_path(user) %></p>
       <p><%= image_tag(user.picture, width: 100) %> -- <%= user.name %> -- <%= user.bio %> View Blog: <%= user.url %> <%= link_to('EDIT', edit_user_path(user.id)) %> <%= link_to('DELETE', user_path(user.id), method: :delete) %></p>
     </div>
  <% end %>

   <hr>

   <%= link_to('Create New User', new_user_path, class: 'btn btn-default') %>

 </div>

walking_tour/app/views/users/new.html.erb
<div class="container">
  <div class="panel-body">
    <%= bootstrap_form_for @user do |form| %>
       
       <%= form.text_field :name %>
       
       <% form.label :url %>
       <%= form.text_field :url %>
       
       <% form.label :picture %>
       <%= form.text_field :picture %>
       
       <% form.label :bio %>
       <%= form.text_field :bio %>
     
     <%= form.submit 'Save', class: 'btn btn-default' %>

    <% end %>
  </div>
</div>

walking_tour/app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.name %></h1>
  <p><%= image_tag(@user.picture, width: 200) %>
  <p><%= @user.bio %></p>
  <p><%= link_to "Link to my site", @user.url, target: 'blank' %></p>
</div>